configuration refactoring, validation, state update (#32)
* add state validation

* use options instead of native config deserialization

* file struct

* update main workflow

* add state updater

* add state updater tests

* ignore vscode folder

* update pr check

* add tests to workflow

* *

* update log level

* add check for image version

* check for app version in main

* update v.1.0.21

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,14 +25,27 @@ jobs:
     - name: get app version
       id: app-version
       run: |
-        echo "::set-output name=APP_VERSION::$(jq -r '.version' ./MakimaBot/appversion.json)"
+        echo "::set-output name=APP_VERSION::$(jq -r '.version' ./MakimaBot/application.config.json)"
+
+    - name: build and run tests
+      run: |
+        docker build --target tests -t makima-tests .
+        docker run makima-tests
 
     - name: build docker image
       run: |  
-        docker build -t makima-bot ./MakimaBot/
+        docker build --target application -t makima-bot .
 
     - name: cr.yandex auth
       run: echo '${{ secrets.REGISTRY_KEY }}' | docker login -u json_key --password-stdin cr.yandex
+
+    - name: check if image version exists
+      run: |
+        IMAGE_NAME="${{ env.registry }}/${{ env.image_name }}:${{ steps.app-version.outputs.APP_VERSION }}"
+        if docker manifest inspect "$IMAGE_NAME" > /dev/null 2>&1; then
+          echo "Error: Image version $IMAGE_NAME already exists! Update application version."
+          exit 1
+        fi
 
     - name: tag docker image
       run: |
