add check for image version

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -23,6 +23,17 @@ jobs:
       id: app-version
       run: |
         echo "::set-output name=APP_VERSION::$(jq -r '.version' ./MakimaBot/application.config.json)"
+
+    - name: cr.yandex auth
+      run: echo '${{ secrets.REGISTRY_KEY }}' | docker login -u json_key --password-stdin cr.yandex
+
+    - name: check if image version exists
+      run: |
+        IMAGE_NAME="${{ env.registry }}/${{ env.image_name }}:${{ steps.app-version.outputs.APP_VERSION }}"
+        if docker manifest inspect "$IMAGE_NAME" > /dev/null 2>&1; then
+          echo "Error: Image version $IMAGE_NAME already exists!"
+          exit 1
+        fi
     
     - name: build and run tests
       run: |
